### ISSUE TITLE
Provide support for cloning existing health check rules

### ISSUE THREAD

**Issue by mdesalvo** [abozaralizadeh/ApiWatchTower#2]

**Comment by abozaralizadeh** [comment]
Thank you @mdesalvo for your suggestion, @ThePiz are you willing to implement this feature?

**Comment by ThePiz** [comment]
@abozaralizadeh  yep, I will get to work on this feature

**Comment by abozaralizadeh** [comment]
Dear @mdesalvo your request is implemented and is now available at https://github.com/abozaralizadeh/ApiWatchTower/commit/0f5d5eb68c72b7f8030e967717a4d48a04763178 

Try it by selecting rules and click on Duplicate, the new rule will be created with the prefix "Copy of xxx":

![image](https://user-images.githubusercontent.com/21077119/125177294-e077cd80-e1da-11eb-904a-1fe2627d9b55.png)
